# Site settings
title: Ersatz.io
email: alex@ersatz.io
description: Ersatz.io makes great, enterprise-grade API Mocks. Leave us your address to be kept up-to-date.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ersatzio.github.io" # the base hostname & protocol for your site

# Social settings
# 500px_url:
# facebook_url:
github_url: https://github.com/ersatzio/
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url:
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
